<<<<<<< Updated upstream
---
- hosts: all
  gather_facts: true
  become: true
  become_user: root
  tasks:
    - dnf:
        name: nginx
=======
---
- hosts: all
  gather_facts: true
  become: true
  become_user: root
  tasks:
    - dnf:
        name: nginx
>>>>>>> Stashed changes
...   