---
- name: "hosts add"
  hosts: all
  become: true
  gather_facts: no
  tasks: 
      - lineinfile:
         path: /etc/hosts
         line: "192.168.88.XX node01"
         insertafter: EOF
         state: present
         
      - lineinfile:
         path: /etc/hosts
         line: "192.168.88.XX node02"
         insertafter: EOF
         state: present
         
      - lineinfile:
         path: /etc/hosts
         line: "192.168.88.XX node03"
         insertafter: EOF
         state: present






...
